version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'weekly'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'all'
    ignored_updates:
      - match:
          dependency_name: 'aws-cdk'
      - match:
          dependency_name: '@aws-cdk*'
    version_requirement_updates: 'widen_ranges'
