name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      REGION: 'us-east-1'
      APP_NAME: 'node-eb'
      REPO_OWNER: 'ryands17'
      REPO_NAME: 'node-beanstalk'
      APP_STAGE_NAME: 'main'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v3
        with:
          node-version: 12.x

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Run Tests
        run: yarn test --ci --coverage --maxWorkers=2
        env:
          CI: true
